server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Mahesh@1810

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:8696

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


