server:
  port: 8696

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maheshphutane/spring-app-config-server
          clone-on-start: true
